### ISSUE TITLE
NoMethodError: undefined method `to_camel' for nil:NilClass

### ISSUE THREAD

**Issue by junsumida** [junsumida/rack-camel_snake#5]
masterに取り込んだところ以下のエラーが...。refinementsのスコープの問題か、Stringの判定がうまくいってない気がする...

```
NoMethodError: undefined method `to_camel' for nil:NilClass
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/refinements.rb:8:in `block in camelize'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/formatter.rb:14:in `block (2 levels) in formatter'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/formatter.rb:7:in `block in formatter'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/formatter.rb:12:in `call'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/formatter.rb:12:in `block in formatter'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/formatter.rb:12:in `each'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/formatter.rb:12:in `reduce'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/formatter.rb:12:in `formatter'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/formatter.rb:14:in `block in formatter'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/formatter.rb:14:in `each'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/formatter.rb:14:in `reduce'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/formatter.rb:14:in `formatter'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake/refinements.rb:8:in `camelize'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake.rb:34:in `block in rewrite_response_body_to_camel'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake.rb:34:in `map!'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake.rb:34:in `rewrite_response_body_to_camel'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/bundler/gems/rack-camel_snake-9f7e17f2fe09/lib/rack/camel_snake.rb:17:in `call'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
    /Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
    /Users/jun.sumida/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
    /Users/jun.sumida/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
    /Users/jun.sumida/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by junsumida** [comment]
`yield`で再帰した場合に、`to_hogehoge`を参照するスコープが変わるみたい。

```
[{"id"=>52, "task_title"=>"a", "order"=>1, "is_done"=>true}, {"id"=>53, "task_title"=>"a", "order"=>2, "is_done"=>true}, {"id"=>54, "task_title"=>"dfa", "order"=>3, "is_done"=>true}, {"id"=>55, "task_title"=>"asdfasd", "order"=>4, "is_done"=>true}, {"id"=>56, "task_title"=>"asdf", "order"=>5, "is_done"=>false}, {"id"=>57, "task_title"=>"adgas", "order"=>1, "is_done"=>false}]
{"id"=>52, "task_title"=>"a", "order"=>1, "is_done"=>true}
NoMethodError: undefined method `to_camel' for nil:NilClass
```

**Comment by rnakano** [comment]
f**\* refinements :bomb:

**Comment by junsumida** [comment]
#6 で修正done!
